# Generated by Django 5.2.4 on 2025-07-29 04:15

import django.db.models.deletion
import games.shotzone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('opponent', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatmap_url', models.URLField(blank=True, null=True)),
                ('point', models.FloatField(default=0.0)),
                ('assist', models.FloatField(default=0.0)),
                ('steal', models.FloatField(default=0.0)),
                ('block', models.FloatField(default=0.0)),
                ('off_reb', models.FloatField(default=0.0)),
                ('def_reb', models.FloatField(default=0.0)),
                ('turnover', models.FloatField(default=0.0)),
                ('games_played', models.IntegerField(default=0)),
                ('shot_zone_stats', models.JSONField(default=dict)),
                ('player_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.player')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(choices=[('made_shot', 'Made Shot'), ('missed_shot', 'Missed Shot'), ('off_reb', 'Offensive Rebound'), ('def_reb', 'Defensive Rebound'), ('steal', 'Steal'), ('assist', 'Assist'), ('block', 'Block'), ('turnover', 'Turnover'), ('made_two', 'Made Two'), ('made_three', 'Made Three'), ('missed_two', 'Missed Two'), ('missed_three', 'Missed Three')], max_length=36)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('shot_zone', models.CharField(blank=True, choices=games.shotzone.ShotZone.choices, db_index=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.season')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatmap_url', models.URLField(blank=True, null=True)),
                ('point', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
                ('steal', models.IntegerField(default=0)),
                ('block', models.IntegerField(default=0)),
                ('off_reb', models.IntegerField(default=0)),
                ('def_reb', models.IntegerField(default=0)),
                ('turnover', models.IntegerField(default=0)),
                ('shot_zone_stats', models.JSONField(default=dict)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player')),
            ],
            options={
                'unique_together': {('player_id', 'game_id')},
            },
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatmap_url', models.URLField(blank=True, null=True)),
                ('games_played', models.IntegerField(default=0)),
                ('point', models.FloatField(default=0.0)),
                ('assist', models.FloatField(default=0.0)),
                ('steal', models.FloatField(default=0.0)),
                ('block', models.FloatField(default=0.0)),
                ('off_reb', models.FloatField(default=0.0)),
                ('def_reb', models.FloatField(default=0.0)),
                ('turnover', models.FloatField(default=0.0)),
                ('shot_zone_stats', models.JSONField(default=dict)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.season')),
            ],
            options={
                'unique_together': {('player_id', 'season_id')},
            },
        ),
    ]
